version: '3.8'

services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    ports:
      - '8081:8080'
    environment:
      SWAGGER_JSON: /json/swagger.json
    volumes:
      - ./json:/json
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '3307:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    restart: "always"
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./application:/var/www/symfony_docker
    depends_on:
      - database
    command: sh -c "composer install && bin/console doctrine:schema:update --force && php-fpm"
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./application:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
